language: python
sudo: true

before_install:
  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
  - pandoc --version

install:
  - sudo apt update
  - sudo apt install ffmpeg
  - pip install tox
  - pip install coveralls

script:
  - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=style
          dist: focal
          sudo: true

        - python: 3.8
          env: TOXENV=coverage
          dist: focal
          sudo: true

        - python: 3.8
          env: TOXENV=docstyle
          dist: focal
          sudo: true

        - python: 3.8
          env: TOXENV=docs
          dist: focal
          sudo: true

        - python: 3.6
          env: TOXENV=py36
          dist: focal
          sudo: true

        - python: 3.7
          env: TOXENV=py37
          dist: focal
          sudo: true

        - python: 3.8
          env: TOXENV=py38
          dist: focal
          sudo: true

        - python: 3.9
          env: TOXENV=py39
          dist: focal
          sudo: true
after_success:
  - coveralls
